using CommunityToolkit.Mvvm.Input;
using SmartExchanger.History;
using SmartExchanger.Models;
using System.ComponentModel;
using System.IO;
using System.Text.Json;
using System.Windows.Input;
using System.Windows.Threading;

namespace SmartExchanger.ViewModels
{
    /// 
    /// NOTE: This file is entierly generated by LLM -> needs careful review and testing!!
    /// 
    public partial class EditorViewModel
    {
        private readonly UndoRedoManager _undoRedoManager;
        private readonly DispatcherTimer _historyCommitTimer;
        private readonly Dictionary<BaseNodeViewModel, PropertyChangedEventHandler> _nodeHistoryPropertyHandlers = new(ReferenceComparer<BaseNodeViewModel>.Instance);
        private readonly Dictionary<Guid, CachedNodeState> _knownNodeStates = new();
        private readonly Dictionary<Guid, Point> _knownNodeLocations = new();

        private PendingNodeStateEdit? _pendingNodeStateEdit;
        private PendingMoveEdit? _pendingMoveEdit;
        private int _historyReplayDepth;
        private bool IsHistoryReplay => _historyReplayDepth > 0;

        public string UndoMenuHeader => (_pendingNodeStateEdit is not null || _pendingMoveEdit is not null) ? "Undo current edit" :
            _undoRedoManager.NextUndoDescription is string description ? $"Undo {description}" : "Undo";
        public string RedoMenuHeader => _undoRedoManager.NextRedoDescription is string description ? $"Redo {description}" : "Redo";

        private bool CanUndo()
        {
            if (_isDisposed || IsTextInputFocused())
            {
                return false;
            }
            return _pendingNodeStateEdit is not null || _pendingMoveEdit is not null || _undoRedoManager.CanUndo;
        }

        private bool CanRedo()
        {
            if (_isDisposed || IsTextInputFocused())
            {
                return false;
            }
            return _pendingNodeStateEdit is not null || _pendingMoveEdit is not null || _undoRedoManager.CanRedo;
        }

        [RelayCommand(CanExecute = nameof(CanUndo))]
        private void Undo()
        {
            if (_isDisposed || IsTextInputFocused())
            {
                return;
            }
            FlushPendingHistory();

            if (!_undoRedoManager.CanUndo)
            {
                return;
            }
            try
            {
                _undoRedoManager.Undo();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Could not undo the last operation. {Environment.NewLine} {Environment.NewLine} {ex.Message}", "Undo failure",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        [RelayCommand(CanExecute = nameof(CanRedo))]
        private void Redo()
        {
            if (_isDisposed || IsTextInputFocused())
            {
                return;
            }
            FlushPendingHistory();

            if (!_undoRedoManager.CanRedo)
            {
                return;
            }
            try
            {
                _undoRedoManager.Redo();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Could not redo the last operation. {Environment.NewLine} {Environment.NewLine} {ex.Message}", "Redo failure",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }


        private void NotifyHistoryAvailabilityChanged()
        {
            UndoCommand.NotifyCanExecuteChanged();
            RedoCommand.NotifyCanExecuteChanged();
            OnPropertyChanged(nameof(UndoMenuHeader));
            OnPropertyChanged(nameof(RedoMenuHeader));
        }
        private void OnUndoRedoManagerStateChanged(object? sender, EventArgs e)
        {
            NotifyHistoryAvailabilityChanged();
        }
        private void OnHistoryCommitTimerTick(object? sender, EventArgs e)
        {
            if (Mouse.LeftButton == MouseButtonState.Pressed)
            {
                return;
            }
            FlushPendingHistory();
        }

        private void RestartHistoryCommitTimer()
        {
            _historyCommitTimer.Stop();
            _historyCommitTimer.Start();
            NotifyHistoryAvailabilityChanged();
        }

        private void FlushPendingHistory()
        {
            _historyCommitTimer.Stop();
            FlushPendingNodeStateHistory();
            FlushPendingMoveHistory();
            NotifyHistoryAvailabilityChanged();
        }

        private void DiscardPendingHistory()
        {
            _historyCommitTimer.Stop();
            _pendingNodeStateEdit = null;
            _pendingMoveEdit = null;
            NotifyHistoryAvailabilityChanged();
        }
        private void ResetUndoRedoHistory()
        {
            DiscardPendingHistory();
            _undoRedoManager.Clear();
            NotifyHistoryAvailabilityChanged();
        }
        private void DisposeUndoRedoHistory()
        {
            _historyCommitTimer.Stop();
            _historyCommitTimer.Tick -= OnHistoryCommitTimerTick;
            _undoRedoManager.StateChanged -= OnUndoRedoManagerStateChanged;
            _pendingNodeStateEdit = null;
            _pendingMoveEdit = null;
            _undoRedoManager.Clear();
            _knownNodeLocations.Clear();
            _knownNodeStates.Clear();
        }

        private void TrackNodeForHistory(BaseNodeViewModel node)
        {
            ArgumentNullException.ThrowIfNull(node);
            if ( _nodeHistoryPropertyHandlers.ContainsKey(node))
            {
                return;
            }
            PropertyChangedEventHandler handler = (_, eArgs) => OnTrackedNodePropertyChanged(node, eArgs);
            _nodeHistoryPropertyHandlers.Add(node, handler);
            node.PropertyChanged += handler;
            _knownNodeLocations[node.Id] = node.Location;
            _knownNodeStates[node.Id] = CaptureNodeStateForHistory(node);
        }
        private void UntrackNodeFromHistory(BaseNodeViewModel node)
        {
            if (_nodeHistoryPropertyHandlers.Remove(node, out PropertyChangedEventHandler? handler))
            {
                node.PropertyChanged -= handler;
            }
            _knownNodeLocations.Remove(node.Id);
            _knownNodeStates.Remove(node.Id);
            if (_pendingNodeStateEdit?.NodeId == node.Id)
            {
                _pendingNodeStateEdit = null;
            }
            if (_pendingMoveEdit is not null)
            {
                _pendingMoveEdit.Before.Remove(node.Id);
                _pendingMoveEdit.After.Remove(node.Id);
                if (_pendingMoveEdit.Before.Count == 0)
                {
                    _pendingMoveEdit = null;
                }
            }
        }
        private void RefreshHistoryStateBaseLines()
        {
            foreach (var node in Nodes)
            {
                _knownNodeLocations[node.Id] = node.Location;
                _knownNodeStates[node.Id] = CaptureNodeStateForHistory(node);
            }
        }

        private void OnTrackedNodePropertyChanged(BaseNodeViewModel node, PropertyChangedEventArgs eventArgs)
        {
            if (eventArgs.PropertyName != nameof(BaseNodeViewModel.Location))
            {
                return;
            }

            Point currentLocation = node.Location;

            if (!_knownNodeLocations.TryGetValue(node.Id, out Point previousLocation))
            {
                _knownNodeLocations[node.Id] = currentLocation;
                return;
            }

            _knownNodeLocations[node.Id] =
                currentLocation;

            if (IsHistoryReplay || ArePointsEqual(previousLocation, currentLocation))
            {
                return;
            }

            if (_pendingNodeStateEdit is not null)
            {
                FlushPendingNodeStateHistory();
            }
            if (_pendingMoveEdit is null)
            {
                _pendingMoveEdit = new PendingMoveEdit();

                _undoRedoManager.ClearRedo();
            }
            if (!_pendingMoveEdit.Before.ContainsKey(node.Id))
            {
                _pendingMoveEdit.Before.Add(node.Id, previousLocation);
            }

            _pendingMoveEdit.After[node.Id] = currentLocation;

            RestartHistoryCommitTimer();
        }

        /// <summary>
        /// Called from OnNodePropertiesChanged after a node's
        /// render-affecting state has changed.
        /// </summary>
        private void HandleNodeStateChangedForHistory(BaseNodeViewModel node)
        {
            CachedNodeState currentState = CaptureNodeStateForHistory(node);

            if (!_knownNodeStates.TryGetValue(node.Id, out CachedNodeState? previousState))
            {
                _knownNodeStates[node.Id] = currentState;
                return;
            }

            _knownNodeStates[node.Id] = currentState;

            if (IsHistoryReplay || AreNodeStatesEqual(previousState, currentState))
            {
                return;
            }

            if (_pendingMoveEdit is not null)
            {
                FlushPendingMoveHistory();
            }

            if (_pendingNodeStateEdit is not null && _pendingNodeStateEdit.NodeId != node.Id)
            {
                FlushPendingNodeStateHistory();
            }

            if (_pendingNodeStateEdit is null)
            {
                _pendingNodeStateEdit =
                    new PendingNodeStateEdit(node.Id, node.Title, previousState, currentState);

                _undoRedoManager.ClearRedo();
            }
            else
            {
                _pendingNodeStateEdit =
                    _pendingNodeStateEdit with
                    {
                        After = currentState
                    };
            }

            RestartHistoryCommitTimer();
        }

        private void FlushPendingNodeStateHistory()
        {
            PendingNodeStateEdit? pending = _pendingNodeStateEdit;

            _pendingNodeStateEdit = null;

            if (pending is null)
            {
                return;
            }

            if (!Nodes.Any(node => node.Id == pending.NodeId))
            {
                return;
            }

            if (AreNodeStatesEqual(pending.Before, pending.After))
            {
                return;
            }

            _undoRedoManager.RecordExecuted(
                new NodeStateHistoryAction(
                    this,
                    pending.NodeId,
                    $"Change {pending.NodeTitle}",
                    pending.Before,
                    pending.After));
        }

        private void FlushPendingMoveHistory()
        {
            PendingMoveEdit? pending = _pendingMoveEdit;

            _pendingMoveEdit = null;

            if (pending is null)
            {
                return;
            }

            var before = new Dictionary<Guid, Point>();
            var after = new Dictionary<Guid, Point>();

            foreach (KeyValuePair<Guid, Point> entry in pending.Before)
            {
                if (!pending.After.TryGetValue(entry.Key, out Point afterPoint))
                {
                    continue;
                }

                if (ArePointsEqual(entry.Value, afterPoint))
                {
                    continue;
                }

                if (!Nodes.Any(node => node.Id == entry.Key))
                {
                    continue;
                }

                before.Add(entry.Key, entry.Value);

                after.Add(entry.Key, afterPoint);
            }

            if (before.Count == 0)
            {
                return;
            }

            string description = before.Count == 1
                    ? "Move node"
                    : $"Move {before.Count} nodes";

            _undoRedoManager.RecordExecuted(
                new MoveNodesHistoryAction(
                    this,
                    description,
                    before,
                    after));
        }

        private CachedNodeState CaptureNodeStateForHistory(BaseNodeViewModel node)
        {
            string stateDirectory = GetHistoryStateDirectory();

            JsonElement state = nodeStateSerializer.CaptureState(node, stateDirectory);

            return new CachedNodeState(stateDirectory, state);
        }


        private string GetHistoryStateDirectory()
        {
            if (!string.IsNullOrWhiteSpace(CurrentProjectPath))
            {
                string fullProjectPath = Path.GetFullPath(CurrentProjectPath);

                string? directory = Path.GetDirectoryName(fullProjectPath);

                if (!string.IsNullOrWhiteSpace(directory))
                {
                    return directory;
                }
            }

            return Path.GetFullPath(AppContext.BaseDirectory);
        }

        private EditorHistorySnapshot CaptureHistorySnapshot()
        {
            string stateDirectory = GetHistoryStateDirectory();

            GraphDocument graph = graphPersistenceService.CaptureDocument(Nodes, Connections, stateDirectory);

            List<Guid> selectedNodeIds =
                SelectedNodes
                    .Where(Nodes.Contains)
                    .Select(node => node.Id).ToList();

            List<ConnectionDocument> selectedConnections = SelectedConnections
                        .Where(Connections.Contains)
                        .Select(CreateConnectionDocument).ToList();

            return new EditorHistorySnapshot
            {
                StateDirectory =  stateDirectory,
                Graph = graph,

                CurrentProjectPath = CurrentProjectPath,

                SelectedNodesIds = selectedNodeIds,

                SelectedConnections = selectedConnections
            };
        }


        private EditorHistorySnapshot CaptureBeforeGraphMutation()
        {
            FlushPendingHistory();
            return CaptureHistorySnapshot();
        }


        private void CommitGraphMutation(string description, EditorHistorySnapshot before)
        {
            if (IsHistoryReplay)
            {
                return;
            }
            EditorHistorySnapshot after = CaptureHistorySnapshot();

            _undoRedoManager.RecordExecuted(new GraphSnapshotHistoryAction(this, description, before, after));
        }

        private static ConnectionDocument CreateConnectionDocument(ConnectionViewModel connection)
        {
            return new ConnectionDocument
            {
                SourceNodeId = connection.Source.Node.Id,
                SourcePortId = connection.Source.Id,
                TargetNodeId = connection.Target.Node.Id,
                TargetPortId = connection.Target.Id
            };
        }


        private void RestoreHistorySnapshot(EditorHistorySnapshot snapshot)
        {
            GraphLoadResult restoredGraph = graphPersistenceService.RestoreDocument(snapshot.Graph, snapshot.StateDirectory);

            using (BeginHistoryReplay())
            {
                CurrentProjectPath = snapshot.CurrentProjectPath;
                ReplaceGraphCore(restoredGraph);

                RestoreHistorySelection(snapshot);
            }

            ShowHistoryWarnings(restoredGraph.Warnings);
        }


        private void RestoreHistorySelection(EditorHistorySnapshot snapshot)
        {
            SelectedNodes.Clear();
            SelectedConnections.Clear();

            var selectedNodeIds = new HashSet<Guid>(snapshot.SelectedNodesIds);

            foreach (BaseNodeViewModel node in Nodes)
            {
                if (selectedNodeIds.Contains(node.Id))
                {
                    SelectedNodes.Add(node);
                }
            }

            foreach ( ConnectionDocument selectedConnection in snapshot.SelectedConnections)
            {
                ConnectionViewModel? connection = Connections.FirstOrDefault(
                        candidate => ConnectionMatchesDocument(candidate, selectedConnection));

                if (connection is not null)
                {
                    SelectedConnections.Add(connection);
                }
            }
        }

        private static bool ConnectionMatchesDocument(ConnectionViewModel connection, ConnectionDocument document)
        {
            return connection.Source.Node.Id == document.SourceNodeId &&
                    string.Equals(connection.Source.Id, document.SourcePortId, StringComparison.Ordinal) &&
                    connection.Target.Node.Id == document.TargetNodeId &&
                    string.Equals(connection.Target.Id, document.TargetPortId, StringComparison.Ordinal);
        }


        private void ApplyNodeStateFromHistory(Guid nodeId, CachedNodeState state)
        {
            BaseNodeViewModel node = Nodes.FirstOrDefault(
                    candidate => candidate.Id == nodeId) ?? throw new InvalidOperationException($"Node '{nodeId}' no longer exists.");

            var warnings = new List<string>();

            using (BeginHistoryReplay())
            {
                nodeStateSerializer.RestoreState(node, state.State, state.StateDirectory, warnings);
                _knownNodeStates[node.Id] = CaptureNodeStateForHistory(node);
            }

            InvalidateGraph(requestGpuPurge: node is TextureSizeNodeViewModel);

            ShowHistoryWarnings(warnings);
        }


        private void ApplyNodeLocationsFromHistory(IReadOnlyDictionary<Guid, Point> locations)
        {
            using (BeginHistoryReplay())
            {
                foreach (KeyValuePair<Guid, Point> entry in locations)
                {
                    BaseNodeViewModel? node = Nodes.FirstOrDefault(candidate => candidate.Id == entry.Key);

                    if (node is null)
                    {
                        continue;
                    }
                    node.Location = entry.Value;

                    _knownNodeLocations[node.Id] = entry.Value;
                }
            }
        }

        private IDisposable BeginHistoryReplay()
        {
            _historyReplayDepth++;
            return new HistoryReplayScope(this);
        }


        private void EndHistoryReplay()
        {
            if (_historyReplayDepth <= 0)
            {
                throw new InvalidOperationException("History replay scope is unbalanced.");
            }

            _historyReplayDepth--;
        }


        private static bool AreNodeStatesEqual(CachedNodeState left, CachedNodeState right)
        {
            return string.Equals(
                left.State.GetRawText(),
                right.State.GetRawText(),
                StringComparison.Ordinal);
        }


        private static bool ArePointsEqual(Point left, Point right)
        {
            const double epsilon = 0.001;

            return Math.Abs(left.X - right.X) <= epsilon &&
                   Math.Abs( left.Y - right.Y) <= epsilon;
        }


        private static void ShowHistoryWarnings(IReadOnlyCollection<string> warnings)
        {
            if (warnings.Count == 0)
            {
                return;
            }

            string warningText =
                string.Join(Environment.NewLine + Environment.NewLine, warnings);

            MessageBox.Show(
                $"The operation was completed, but some resources could not be restored: {Environment.NewLine} {Environment.NewLine} {warningText}",
                "Undo/redo completed with warnings",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }


        private sealed record CachedNodeState(string StateDirectory, JsonElement State);

        private sealed record PendingNodeStateEdit(Guid NodeId, string NodeTitle, CachedNodeState Before, CachedNodeState After);

        private sealed class PendingMoveEdit
        {
            public Dictionary<Guid, Point> Before { get; } = new();
            public Dictionary<Guid, Point> After { get; } = new();
        }

        private sealed class HistoryReplayScope : IDisposable
        {
            private EditorViewModel? _owner;
            public HistoryReplayScope(EditorViewModel owner)
            {
                _owner = owner;
            }

            public void Dispose()
            {
                EditorViewModel? owner = Interlocked.Exchange(ref _owner, null);
                owner?.EndHistoryReplay();
            }
        }


        private sealed class GraphSnapshotHistoryAction : IUndoableAction
        {
            private readonly EditorViewModel _editor;
            private readonly EditorHistorySnapshot _before;
            private readonly EditorHistorySnapshot _after;

            public string Description { get; }

            public GraphSnapshotHistoryAction(EditorViewModel editor, string description,
                EditorHistorySnapshot before, EditorHistorySnapshot after)
            {
                _editor = editor;
                Description = description;
                _before = before;
                _after = after;
            }
            public void Undo()
            {
                _editor.RestoreHistorySnapshot(_before);
            }
            public void Redo()
            {
                _editor.RestoreHistorySnapshot(_after);
            }
        }

        private sealed class NodeStateHistoryAction : IUndoableAction
        {
            private readonly EditorViewModel _editor;
            private readonly Guid _nodeId;
            private readonly CachedNodeState _before;
            private readonly CachedNodeState _after;

            public string Description { get; }

            public NodeStateHistoryAction(EditorViewModel editor, Guid nodeId, string description,
                CachedNodeState before, CachedNodeState after)
            {
                _editor = editor;
                _nodeId = nodeId;
                Description = description;
                _before = before;
                _after = after;
            }

            public void Undo()
            {
                _editor.ApplyNodeStateFromHistory(_nodeId, _before);
            }

            public void Redo()
            {
                _editor.ApplyNodeStateFromHistory(_nodeId, _after);
            }
        }


        private sealed class MoveNodesHistoryAction : IUndoableAction
        {
            private readonly EditorViewModel _editor;

            private readonly IReadOnlyDictionary<Guid, Point> _before;

            private readonly IReadOnlyDictionary<Guid, Point> _after;

            public string Description { get; }

            public MoveNodesHistoryAction(EditorViewModel editor, string description,
                IReadOnlyDictionary<Guid, Point> before, IReadOnlyDictionary<Guid, Point> after)
            {
                _editor = editor;
                Description = description;
                _before = before;
                _after = after;
            }

            public void Undo()
            {
                _editor.ApplyNodeLocationsFromHistory(_before);
            }
            public void Redo()
            {
                _editor.ApplyNodeLocationsFromHistory( _after);
            }
        }
    }
}
