<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<ApplicationIcon>Assets\Icons\small-icon.ico</ApplicationIcon>
	<InterceptorsNamespaces>
		$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration
	</InterceptorsNamespaces>
  </PropertyGroup>

	<PropertyGroup>
		<Version>1.2.0</Version>
		<AssemblyVersion>1.2.0.0</AssemblyVersion>
		<FileVersion>1.2.0.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />

		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="HelixToolkit.Wpf.SharpDX" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="Nodify" Version="7.3.0" />
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
	<PackageReference Include="SkiaSharp.Direct3D.Vortice" Version="4.150.1" />
	<PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
	<PackageReference Include="Vortice.DXGI" Version="3.8.3" />

	  <PackageReference Include="JeremyAnsel.HLSL.Targets" Version="2.0.29" PrivateAssets="all" />
  </ItemGroup>

	<ItemGroup>
		<HLSLShader Include="Shaders\MaterialPreview\Helix\PS\psMeshPBRTriplanar.hlsl">
			<ShaderProfile>ps_4_0</ShaderProfile>
		</HLSLShader>

		<HLSLShader Include="Shaders\MaterialPreview\Helix\PS\psMeshPBRTriplanarOIT.hlsl">
			<ShaderProfile>ps_4_0</ShaderProfile>
		</HLSLShader>

		<HLSLShader Include="Shaders\MaterialPreview\Helix\PS\psMeshPBRTriplanarOITDP.hlsl">
			<ShaderProfile>ps_4_0</ShaderProfile>
		</HLSLShader>
	</ItemGroup>


	<ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Repositories\" />
    <Folder Include="Shaders\MaterialPreview\Helix\Common\" />
  </ItemGroup>
  <ItemGroup>
	  <Content Include="Shaders\**\*.sksl">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\Icons\icon.png" />
    <None Remove="Assets\Icons\large-logo.png" />
    <None Remove="Assets\Icons\small-icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Icons\small-icon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Icons\icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\large-logo.png" />
  </ItemGroup>
  <ItemGroup>
	  <None Update="Assets\EnvironmentMaps\**\*.dds">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </None>
  </ItemGroup>

</Project>
